### ISSUE TITLE
Question about "forking/copying"

### ISSUE THREAD

**Issue by bassmanitram** [adamjq/aws-secretsmanager-cache-rust#13]
Hey Adam ...

(Never done this - try to directly contact a member with whom I have zero other interaction)

I'm about to royally rip you off, if you don't mind. In effect I'm want to copy this repo wholesale and, basically, change every mention of Secrets Manager to SSM Parameter to create the same thing for SSM Parameter caching. I really like your API better than I like those of other similar things out there. And, of course, you'll get credit for all the code, whereas I will simply claim credit for the sed command that converts it to SSM Parameters.

However, if you object, I vow to stop right here and seek another solution.

(I have created it - https://github.com/bassmanitram/aws-ssm-parameter-cache-rust - but will remove it if you deem that appropriate)

**Comment by adamjq** [comment]
Hey Martin, no problem from me - it sounds like a good idea and something I'd use. I'd thought about doing that myself but didn't find the time

This crate is heavily inspired by https://github.com/aws/aws-secretsmanager-caching-go anyway
